# .github/workflows/backend-deploy.yml
name: Build and deploy Node.js app to Azure Web App - LS2FABackend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: backend/package.json
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci --production
          
      - name: Create web.config for Azure App Service
        run: |
          cd backend
          echo "🔧 Creating web.config for Azure App Service..."
          cat > web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="iisnode" path="src/server.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="src/server.js"/>
                  </rule>
                </rules>
              </rewrite>
              <httpErrors existingResponse="PassThrough" />
              <iisnode 
                node_env="production"
                nodeProcessCountPerApplication="1"
                maxConcurrentRequestsPerProcess="1024"
                watchedFiles="*.js"
                loggingEnabled="true"
                devErrorsEnabled="false"
              />
            </system.webServer>
          </configuration>
          EOF
          echo "✅ web.config created"
          
      - name: Create deployment package from backend folder
        run: |
          cd backend
          zip -r ../backend-release.zip . \
            -x "node_modules/.cache/*" \
            -x "*.log" \
            -x ".env*" \
            -x ".git*"
          echo "✅ Backend package created from backend/ folder"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          
      - name: Unzip artifact for deployment
        run: |
          mkdir backend
          unzip backend-release.zip -d backend
          echo "✅ Backend folder created:"
          ls -la backend
          
          # Vérifier les fichiers critiques
          echo "🔍 Verification:"
          ls -la backend/src/server.js && echo "✅ server.js found" || echo "❌ server.js MISSING"
          ls -la backend/package.json && echo "✅ package.json found" || echo "❌ package.json MISSING"
          ls -la backend/web.config && echo "✅ web.config found" || echo "❌ web.config MISSING"
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BF766D5A20142FD98FE5C9A0AC83352 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3319CE4BA45F421B8738BADAE4CEA94A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7F935D1C76E748C79F07EC76D990ECAF }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LS2FABackend'
          slot-name: 'Production'
          package: backend/
          
      - name: Test deployment
        run: |
          echo "⏳ Waiting for deployment (90s)..."
          sleep 90
          
          echo "🧪 Testing backend endpoints..."
          
          # Test 1: Root endpoint
          echo "📍 Testing root endpoint..."
          curl -f -s https://ls2fabackend-fthub6cvegdeagbv.westeurope-01.azurewebsites.net/ && echo "✅ Root OK" || echo "❌ Root failed"
          
          # Test 2: Health endpoint
          echo "📍 Testing health endpoint..."
          curl -f -s https://ls2fabackend-fthub6cvegdeagbv.westeurope-01.azurewebsites.net/api/v1/health && echo "✅ Health OK" || echo "❌ Health failed"
          
          # Test 3: API base
          echo "📍 Testing API base..."
          curl -f -s https://ls2fabackend-fthub6cvegdeagbv.westeurope-01.azurewebsites.net/api/v1 && echo "✅ API OK" || echo "❌ API failed"
          
          echo "✅ Testing completed"
