name: Build and deploy Node.js app to Azure Web App - lsapi2fanackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Zip backend for deployment
        run: |
          cd backend
          zip -r ../release.zip . \
            -x "node_modules/*" \
            -x "*.log" \
            -x ".env*" \
            -x ".git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_726DD676AA9B4D9A81F549A73E455AE3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6AFF550B307743F4A573D117F84D96F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_03E083A6FB9B49529750A0A94CC3CD89 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lsapi2fanackend'
          slot-name: 'Production'
          package: .

      - name: Health check
        run: |
          echo "⏳ Waiting 30s for app to boot..."
          sleep 30
          curl -f https://lsapi2fanackend.azurewebsites.net/api/v1/health || echo "❌ Health check failed"
